engines:
  pep8:
    enabled: true

ratings:
   paths:
   - "**.py"

exclude_paths:
  - "core/migrations/"
  - "core/static/css/"
  - "core/static/fonts/"
  - "core/static/js/language/"
  - "core/static/js/locales/"
  - "core/static/js/validator/"
  - "core/static/js/"
